user_name=input("what is your name: ")
surname= input("whats your surname: ")
age= input("whats your age: ")
tall=input("how tall are you: ")
fc_acc=input("what is the name of your facebook account: ")
occupation=input("what is your occupation: ")
parent_name=input("what is the name of the parent: ")
favorite_food=input("what is your favorite food: ")
email_adress=input("what is your email adress: ")
season=input("what is your favorite season: ")
movie=input("what is your favorite movie")
novel=input("what is your favorite novel: ")
favorite_football_team=input("what is your favorite football team: ")
# print("man tkva rom chemi saxelia: " + user_name)
# print("man tkva rom chemi gvaria: " + surname)
# print("man tkva rom chemi asakia: " + age)
# print("man tkva rom chemi eccia: " + fc_acc)
# print("man tkva rom chemi samusaoa: " + occupation)
# print("man tkva rom chemi mshoblis saxelia: " + parent_name)
# print("man tkva rom chemi sayvareli sakvebia: " + favorite_food)
# print("man tkva rom chemi emailia: " + email_adress)
# print(" man tkva rom chemi sayvareli sezonia: " + season)
# print("man tkva rom chemi sayvareli kinoa: " + movie)
# print("man tkva rom chemi sayvareli romania: " + novel)
# print("man tkva rom chemi savareli gundia: " + favorite_football_team) 
print("man tkva rom chemi saxelia: " + user_name + "/" + "man tkva rom chemi gvaria: " + surname + "/" + "man tkva rom chemi asakia: " + age + "/" + "man tkva rom chemi eccia: " + fc_acc + "/" + "man tkva rom chemi samusaoa: " + occupation + "/" + "man tkva rom chemi mshoblis saxelia: " + parent_name + "/" + "man tkva rom chemi sayvareli sakvebia: " + favorite_food + "/" + "man tkva rom chemi emailia: " + email_adress + "/" + " man tkva rom chemi sayvareli sezonia: " + season + "/" + "man tkva rom chemi sayvareli kinoa: " + movie + "/" + "man tkva rom chemi sayvareli romania: " + novel + "/" + "man tkva rom chemi savareli gundia: " + favorite_football_team ) 



